before:
  hooks:
    - make deps
builds:
- env:
  - CGO_ENABLED=0
  ## Overlaps with what is defined in Makefile - we should find a away of having it defined only once
  - PACKAGE_NAME=github.com/bartoszmajsak/github-changelog-generator
  - RELEASE=true
  main: ./cmd/
  binary: ghc
  goos:
    - linux
    - darwin
  goarch:
    - 386
    - amd64
  ldflags:
    - -s -w -X {{.Env.PACKAGE_NAME}}/version.Release={{.Env.RELEASE}} -X {{.Env.PACKAGE_NAME}}/version.Version=v{{.Version}} -X {{.Env.PACKAGE_NAME}}/version.Commit={{.ShortCommit}} -X {{.Env.PACKAGE_NAME}}/version.BuildTime={{.Date}}
archives:
  - name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
