defaults:
  docker:
    - image: &golang-img circleci/golang:1.13.4

version: 2.1

jobs:
  ## Regular build running unit tests and linters
  build:
    working_directory: /go/src/github.com/bartoszmajsak/github-changelog-generator
    docker:
      - image: *golang-img
    steps:
      - checkout
      - restore_cache:
          keys:
            - vendor-cache-{{ checksum "Gopkg.lock" }}
      - run:
          name: "Runs the build"
          command: make build-ci
      - save_cache:
          key: vendor-cache-{{ checksum "Gopkg.lock" }}
          paths:
            - ./vendor

  release:
    working_directory: /go/src/github.com/bartoszmajsak/github-changelog-generator
    docker:
      - image: *golang-img
    steps:
      - checkout
      - run:
          name: "Release it!"
          command: |
            curl -sL https://git.io/goreleaser | bash -s -- release --rm-dist

  workflows:
    version: 2.1
    circleci_build:
      jobs:
        - build
    circleci_e2e_tests:
      jobs:
        - e2e_tests_local
        - e2e_tests_remote
    circleci_release:
      jobs:
        - build:
            filters:
              tags:
                only: /^v.*/
              branches:
                ignore: /.*/
        - release:
            requires:
              - build
            filters:
              tags:
                only: /^v.*/
              branches:
                ignore: /.*/
